# -*- coding: utf-8 -*-
# @Author: Daniel Gomes
# @Date:   2022-10-15 19:59:44
# @Last Modified by:   Daniel Gomes
# @Last Modified time: 2022-10-18 16:18:31

# this parameters should be adapted to
# the charateristics of your destination VM
tunnel-as-a-service-sd:
        ssh-hostname: 10.0.12.106
        ssh-username: ubuntu
        ssh-password: ubuntu
