# @Author: Daniel Gomes
# @Date:   2023-02-02 15:20:05
# @Last Modified by:   Daniel Gomes
# @Last Modified time: 2023-02-16 17:06:29
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-serv
  labels:
{{ include "eechart.labels" . | indent 4 }}  
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "eechart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.service_port }}
      targetPort: {{ .Values.service.container_port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "eechart.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "eechart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.grcp.service_port }}
      targetPort: {{ .Values.service.grcp.container_port }}